---
version: "3"

services:
  potterhat:
    # Use eWallet's base to avoid maintaining another one.
    image: omisegoimages/ewallet-builder:v1.2
    restart: always
    environment:
      RPC_PORT: "8545"
    ports:
      - "8545:8545"
